name: flutter_weather_forecast
description: A custom weather forecast widget for Turkey.Weather data provided by the General Directorate of Meteorology.
version: 1.2.0
homepage: https://github.com/coskuncay/flutter_weather_forecast
repository: https://github.com/coskuncay/flutter_weather_forecast

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets: 
    - packages/flutter_weather_forecast/assets/images/a.png
    - packages/flutter_weather_forecast/assets/images/ab.png
    - packages/flutter_weather_forecast/assets/images/dmn.png
    - packages/flutter_weather_forecast/assets/images/dy.png
    - packages/flutter_weather_forecast/assets/images/gkr.png
    - packages/flutter_weather_forecast/assets/images/gsy.png
    - packages/flutter_weather_forecast/assets/images/hky.png
    - packages/flutter_weather_forecast/assets/images/k.png
    - packages/flutter_weather_forecast/assets/images/kf.png
    - packages/flutter_weather_forecast/assets/images/kgy.png
    - packages/flutter_weather_forecast/assets/images/kkr.png
    - packages/flutter_weather_forecast/assets/images/ksy.png
    - packages/flutter_weather_forecast/assets/images/ky.png
    - packages/flutter_weather_forecast/assets/images/msy.png
    - packages/flutter_weather_forecast/assets/images/pb.png
    - packages/flutter_weather_forecast/assets/images/pus.png
    - packages/flutter_weather_forecast/assets/images/sck.png
    - packages/flutter_weather_forecast/assets/images/sis.png
    - packages/flutter_weather_forecast/assets/images/sy.png
    - packages/flutter_weather_forecast/assets/images/y.png
    - packages/flutter_weather_forecast/assets/images/yky.png
    - packages/flutter_weather_forecast/assets/images/r.png
    - packages/flutter_weather_forecast/assets/images/kky.png
    - packages/flutter_weather_forecast/assets/images/hy.png
    - packages/flutter_weather_forecast/assets/images/hsy.png
    - packages/flutter_weather_forecast/assets/images/cb.png
    - packages/flutter_weather_forecast/assets/images/a.png
    - packages/flutter_weather_forecast/assets/images/hhy.png

  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
